---
name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.11.0
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
        working-directory: ./server
      - run: npm run start
      - run: sudo apt-get install build-essential
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
